apiVersion: v1
kind: Service
metadata:
  name: {{ include "auditcore.fullname" . }}-backend
  labels:
    app: {{ include "auditcore.name" . }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "auditcore.name" . }}
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auditcore.name" . }}-frontend
  labels:
    app: {{ include "auditcore.name" . }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "auditcore.name" . }}
    component: frontend
