"""init auditcore"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '20260628_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS inventory')
    op.create_table('company', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('sector', sa.String(length=255), nullable=False), sa.Column('tier', sa.Enum('essential','advanced','elite', name='company_tier'), nullable=False), sa.Column('deployment_mode', sa.Enum('onpremise','cloud', name='deployment_mode'), nullable=False), sa.Column('tenant_schema', sa.String(length=255), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('branch', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('location', sa.String(length=255), nullable=False))
    op.create_table('user_account', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('email', sa.String(length=255), nullable=False, unique=True), sa.Column('hashed_password', sa.String(length=255), nullable=False), sa.Column('full_name', sa.String(length=255), nullable=False), sa.Column('role', sa.Enum('owner','gm','manager','auditor','admin','appowner', name='user_role'), nullable=False), sa.Column('branch_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('branch.id', ondelete='SET NULL')), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'), sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True), sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('audit_task', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('branch_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('branch.id', ondelete='SET NULL')), sa.Column('title', sa.String(length=255), nullable=False), sa.Column('status', sa.String(length=50), nullable=False), sa.Column('assigned_to_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='SET NULL')), sa.Column('due_at', sa.DateTime(timezone=True), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('document', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('branch_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('branch.id', ondelete='SET NULL')), sa.Column('uploaded_by_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='SET NULL')), sa.Column('original_filename', sa.String(length=255), nullable=False), sa.Column('mime_type', sa.String(length=255), nullable=False), sa.Column('file_size', sa.Integer(), nullable=False), sa.Column('encrypted_blob', sa.LargeBinary(), nullable=False), sa.Column('metadata_json', sa.JSON(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('document_certification', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('document_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('document.id', ondelete='CASCADE'), nullable=False), sa.Column('certified_by_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='SET NULL')), sa.Column('certification_status', sa.String(length=50), nullable=False), sa.Column('notes', sa.Text(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('audit_ledger', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('actor_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='SET NULL')), sa.Column('action_type', sa.String(length=100), nullable=False), sa.Column('action_payload', sa.JSON(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('analytics_outputs', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('output_type', sa.String(length=100), nullable=False), sa.Column('payload', sa.JSON(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('waste_map_items', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('category', sa.String(length=100), nullable=False), sa.Column('description', sa.Text(), nullable=False), sa.Column('impact_score', sa.Integer(), nullable=False, server_default='0'), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('risk_alerts', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('severity', sa.String(length=50), nullable=False), sa.Column('message', sa.Text(), nullable=False), sa.Column('status', sa.String(length=50), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    op.create_table('ocr_extraction', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('document_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('document.id', ondelete='CASCADE'), nullable=False, unique=True), sa.Column('status', sa.String(length=50), nullable=False), sa.Column('extracted_data', sa.JSON(), nullable=False), sa.Column('confidence_map', sa.JSON(), nullable=False), sa.Column('raw_text', sa.Text(), nullable=True), sa.Column('page_count', sa.Integer(), nullable=False, server_default='1'), sa.Column('processing_time_ms', sa.Integer(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('certified_at', sa.DateTime(timezone=True), nullable=True), sa.Column('certified_by_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='SET NULL')))
    op.create_table('daily_task', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('auditor_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='CASCADE'), nullable=False), sa.Column('task_type', sa.String(length=50), nullable=False), sa.Column('title', sa.String(length=255), nullable=False), sa.Column('status', sa.String(length=50), nullable=False), sa.Column('source_document_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('document.id', ondelete='SET NULL')), sa.Column('due_at', sa.DateTime(timezone=True), nullable=False), sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True), sa.Column('sla_minutes', sa.Integer(), nullable=False), sa.Column('demerit_points', sa.Integer(), nullable=False, server_default='0'), sa.Column('severity', sa.String(length=20), nullable=False, server_default='normal'), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    op.create_table('notification_queue', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('company_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('company.id', ondelete='CASCADE'), nullable=False), sa.Column('channel', sa.String(length=50), nullable=False), sa.Column('destination', sa.String(length=255), nullable=False), sa.Column('message', sa.Text(), nullable=False), sa.Column('severity', sa.String(length=20), nullable=False), sa.Column('status', sa.String(length=20), nullable=False), sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'), sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_table('permission', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('code', sa.String(length=100), nullable=False, unique=True), sa.Column('name', sa.String(length=255), nullable=False), sa.Column('category', sa.String(length=100), nullable=False), sa.Column('description', sa.Text(), nullable=True))
    op.create_table('role_permission', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('role', sa.Enum('owner','gm','manager','auditor','admin','appowner', name='role_permission_role'), nullable=False), sa.Column('permission_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('permission.id', ondelete='CASCADE'), nullable=False), sa.UniqueConstraint('role', 'permission_id', name='uq_role_permission'))
    op.create_table('user_permission_override', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='CASCADE'), nullable=False), sa.Column('permission_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('permission.id', ondelete='CASCADE'), nullable=False), sa.Column('action', sa.Enum('grant','revoke', name='override_action'), nullable=False), sa.Column('reason', sa.Text(), nullable=False), sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True), sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('user_account.id', ondelete='SET NULL')), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("""
    CREATE OR REPLACE FUNCTION set_user_role(role text) RETURNS void AS $$
    BEGIN
        PERFORM set_config('app.current_user_role', role, true);
    END;
    $$ LANGUAGE plpgsql;
    """)
    for table in ['analytics_outputs', 'waste_map_items', 'risk_alerts']:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY')
        op.execute(f"CREATE POLICY auditor_no_access_{table} ON {table} FOR ALL USING (current_setting('app.current_user_role', true) != 'auditor')")


def downgrade() -> None:
    pass
