#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
echo "Docker-enabled verification flow:"
echo ""
echo "1) Start services"
echo "   docker compose up -d postgres redis backend celery-worker celery-beat"
echo ""
echo "2) Run migrations if needed"
echo "   docker compose exec -T backend alembic upgrade head"
echo ""
echo "3) Seed data"
echo "   ./scripts/setup.sh"
echo ""
echo "4) Run tests"
echo "   docker compose exec -T backend pytest -q backend/app/tests/test_phase2.py backend/app/tests/test_integration_api.py"
echo ""
echo "5) Run manual API flows"
echo "   See API_TESTS.md"
